name: dotnet
on: 
- push
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 7.0.x
      - name: Publish with dotnet
        run: dotnet publish --configuration Release --output build
      - name: Deploy to Github Pages
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: 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
          BASE_BRANCH: main
          BRANCH: gh-pages
          FOLDER: build/wwwroot
          SINGLE_COMMIT: true
